name: Deploy Ops Infra
on:
  push:
    paths:
      - 'infra/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: python-version: '3.9'
    - run: pip install aws-cdk-lib constructs
    - run: cdk deploy OpsStack --require-approval never
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
